server {
	listen 443 ssl;			# ipv4
	listen [::]:443 ssl;	# ipv6

	server_name lgaudino.42.fr;

	# load the ssl certificate keys
	ssl_certificate /etc/nginx/ssl/inception.crt;		# public key
	ssl_certificate_key /etc/nginx/ssl/inception.key;	# private key

	# define the tls protocols (as subject)
	ssl_protocols TLSv1.2 TLSv1.3;

	# dir of website
	root /var/www/html;

	# index page
	index index.php index.html;

	# redirect the requets
	location / {
		try_files $uri $uri/ /index.php$is_args$args;
	}

	# php cgi proxy
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$; # take the file name and args
		fastcgi_pass wordpress:9000; # container name : port
		fastcgi_index index.php;
		include fastcgi.conf;		# include default params
	}
}