[www]
; PHP-FPM user and group
user = www-data
group = www-data
; nginx connection
listen = 9000
listen.owner = www-data
listen.group = www-data
; setup the Process Manager
pm = dynamic
pm.max_children = 5 ; max php process
pm.start_servers = 2
pm.min_spare_servers = 1 ; always at least one process waiting for new users
pm.max_spare_servers = 3 ; at maximum 3 process in waiting
; disable env reset (useful for .env)
clear_env = no